=== GBPA/OpenGTS/dcservers.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>
 
<!ELEMENT DCServerConfig (Include*, DCServer+)>
	<!ATTLIST DCServerConfig bindAddress CDATA #IMPLIED>
	<!ATTLIST DCServerConfig backlog CDATA #IMPLIED>
	<!ATTLIST DCServerConfig portOffset CDATA #IMPLIED>
	<!ATTLIST DCServerConfig includeDir CDATA #IMPLIED>

<!ELEMENT DCServer (Description, ModelNames?, Attributes?, UniqueIDPrefix?, ListenPorts, Properties?, GlobalProperties?, EventCodeMap?, Commands?)>
	<!ATTLIST DCServer name     CDATA #REQUIRED>
	<!ATTLIST DCServer protocol CDATA #IMPLIED>

<!ELEMENT ModelNames (#PCDATA)>

<!ELEMENT Attributes (#PCDATA)>

<!ELEMENT ListenPorts (#PCDATA)>
	<!ATTLIST ListenPorts tcpPort CDATA #IMPLIED>
	<!ATTLIST ListenPorts udpPort CDATA #IMPLIED>

<!ELEMENT UniqueIDPrefix (#PCDATA)>

<!ELEMENT Properties (Property+)>

<!ELEMENT GlobalProperties (Property+)>

<!ELEMENT Property (#PCDATA)>
	<!ATTLIST Property key CDATA #IMPLIED>

<!ELEMENT EventCodeMap (Code+)>
	<!ATTLIST EventCodeMap enabled CDATA #IMPLIED>

<!ELEMENT Code (#PCDATA)>
	<!ATTLIST Code key CDATA #IMPLIED>

<!ELEMENT Commands (AclName?, Command+)>
	<!ATTLIST Commands dispatchHost CDATA #IMPLIED>
	<!ATTLIST Commands dispatchPort CDATA #IMPLIED>

<!ELEMENT Command (AclName?, Type, Description, String, Arg*, StatusCode?)>
	<!ATTLIST Command name      CDATA #IMPLIED>
	<!ATTLIST Command hasArgs   CDATA #IMPLIED>
	<!ATTLIST Command expectAck CDATA #IMPLIED>
	<!ATTLIST Command enabled   CDATA #IMPLIED>

<!ELEMENT Type (#PCDATA)>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT AclName (#PCDATA)>
	<!ATTLIST AclName default CDATA #IMPLIED>

<!ELEMENT String (#PCDATA)>
	<!ATTLIST String protocol CDATA #IMPLIED>

<!ELEMENT Arg (#PCDATA)>
	<!ATTLIST Arg name         CDATA #IMPLIED>
	<!ATTLIST Arg length       CDATA #IMPLIED>
	<!ATTLIST Arg defaultValue CDATA #IMPLIED>
	<!ATTLIST Arg readOnly     CDATA #IMPLIED>

<!ELEMENT StatusCode (#PCDATA)>

<!ELEMENT Include (#PCDATA)>
	<!ATTLIST Include dir CDATA #IMPLIED>
	<!ATTLIST Include file CDATA #IMPLIED>
	<!ATTLIST Include optional CDATA #IMPLIED>

=== GBPA/OpenGTS/dcservers.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE DCServerConfig SYSTEM "dcservers.dtd" >

<!-- 
  =======================================================================================
  Project: OpenGTS - Open GPS Tracking System
  URL    : http://www.opengts.org
  File   : dcservers.xml
  =======================================================================================
-->

<!-- 
  =======================================================================================
  DCServerConfig tag attributes:
    "bindAddress" - the IP address (or host) interface to which these servers will "bind"
       Typically only necessary if this computer has more than one network interface.
       If this value is blank, then the server will bind to all network interfaces.
    "backlog" - The maximum queue length for incoming connection indications (a request to 
       connect) is set to this backlog value.  If a connection indication arrives when the 
       queue is full, the connection is refused.  (see "java.net.ServerSocket")
    "portOffset" - An offset value to add to the specified ports before setting up the
       port 'listeners'.  This value should typically remain '0'.
  Notes:
    - The general ports used for OpenGTS device communication server (DCS) modules are
      typically in the range 31000 to 31999.  However these can be changed on the 
      "ListenPorts" tag.
  =======================================================================================
-->

<!-- ================================================================================ -->
<DCServerConfig
    bindAddress=""
    backlog=""
    includeDir="dcservers"
    >
    <!-- ================================================================================
     === Standard properties:
     ===    uniqueIdPrefix          - [String]
     ===    commandProtocol         - [tcp|udp|sms]
     ===    ackResponsePort         - [int]
     ===    clientCommandPort       - [int]
     ===    clientCommandPort.udp   - [int]
     ===    clientCommandPort.tcp   - [int]
     ===    tcpIdleTimeoutMS        - [long]
     ===    tcpPacketTimeoutMS      - [long]
     ===    tcpSessionTimeoutMS     - [long]
     ===    udpIdleTimeoutMS        - [long]
     ===    udpPacketTimeoutMS      - [long]
     ===    udpSessionTimeoutMS     - [long]
     ===    minimumSpeedKPH         - [double]
     ===    estimateOdometer        - [boolean]
     ===    simulateGeozones        - [boolean]
     ===    simulateDigitalInputs   - [boolean]
     ===    minimumMovedMeters      - [double]
     ===    saveRawDataPackets      - [boolean]
     ===    startStopSupported      - [boolean]
     ===    statusLocationInMotion  - [boolean] Translate Location to InMotion
     -->

    <!-- ================================================================================ -->
    <Include file="dcserver_template.xml" optional="true"/>
    <DCServer name="template">
    
        <!--
         === DCS Description
         -->
        <Description><![CDATA[
            Example Template Server
            ]]></Description>
            
        <!-- 
         === Possible Unique-ID prefixes ("*" means that the mobile-id is used as-is)
         === Example: If the mobile-id is "123456789012345", then the "Unique ID" value
         === set in the Device admin page can be one of the following:
         ===   imei_123456789012345
         ===   123456789012345
         ===   <etc.>
         -->
        <UniqueIDPrefix><![CDATA[
            template_
            imei_
            *
            ]]></UniqueIDPrefix>
            
        <!-- 
         === Listen ports
         -->
        <ListenPorts 
            tcpPort="31200" 
            udpPort="31200"
            />
            
        <!--
         === DCS runtime properties
         -->
        <Properties>
            <!-- <Property key="parseFormat">1</Property>               -->
            <!-- <Property key="minimumSpeedKPH">4.0</Property>         -->
            <!-- <Property key="estimateOdometer">true</Property>       -->
            <!-- <Property key="simulateGeozones">true</Property>       -->
            <!-- <Property key="simulateDigitalInputs">0xFF</Property>  -->
            <!-- <Property key="tcpIdleTimeoutMS">5000</Property>       -->
            <!-- <Property key="tcpPacketTimeoutMS">10000</Property>    -->
            <!-- <Property key="tcpSessionTimeoutMS">20000</Property>   -->
            </Properties>
        
    </DCServer>

    <!-- ================================================================================ -->
    <DCServer name="gtsdmtp">
    
        <!--
         === DCS Description
         -->
        <Description><![CDATA[
            OpenDMTP
            ]]></Description>
            
        <!-- 
         === Listen ports
         -->
        <ListenPorts 
            tcpPort="31000" 
            udpPort="31000"
            />
            
        <!--
         === DCS runtime properties
         -->
        <Properties>
            <Property key="firstSessionNegotiation">true</Property>
            <Property key="udpReturnResponse">true</Property>
            <Property key="simulateGeozones">false</Property>
            <!-- <Property key="customEvent.55">1|H|0|2 2|H|0|4 6|H|0|8 8|H|0|2 9|H|0|2 10|H|0|3 11|H|0|3 12|H|0|4 93|H|0|2 88|H|0|2 82|H|0|4 4|H|0|1</Property> -->
            </Properties>
            
    </DCServer>

    <!-- ================================================================================ -->
    <DCServer name="aspicore">
    
        <!--
         === DCS Description
         -->
        <Description><![CDATA[
            Aspicore GSM Tracker
            ]]></Description>
            
        <!-- 
         === Possible Unique-ID prefixes ("*" means that the mobile-id is used as-is)
         === Example: If the mobile-id is "123456789012345", then the "Unique ID" value
         === set in the Device admin page can be one of the following:
         ===   imei_123456789012345
         ===   123456789012345
         ===   <etc.>
         -->
        <UniqueIDPrefix><![CDATA[
            asp_
            s60_
            imei_
            *
            ]]></UniqueIDPrefix>
            
        <!-- 
         === Listen ports
         -->
        <ListenPorts 
            tcpPort="31265" 
            udpPort="31265"
            />
            
        <!--
         === DCS runtime properties
         -->
        <Properties>
        
            <Property key="minimumSpeedKPH">3.0</Property>
            <!--
             === "minimumSpeedKPH" - The minimum speed value, below which the device will
             === be assumed to be stopped, and the 'speed' will be explicitly set to '0.0'.
             -->

            <Property key="statusLocationInMotion">true</Property>
            <!--
             === "statusLocationInMotion" - If true, the DCS will replace an event with a
             === STATUS_LOCATION status code with a STATUS_MOTION_IN_MOTION status code, if
             === the speed of the vehicle is greater than zero.
             -->

            <Property key="minimumMovedMeters">0</Property>
            <!--
             === "minimumMovedMeters" - if > '0', subsequent received events will be omitted if
             === they are within the specified number of meters to the previous event.  Useful
             === for eliminating multiple events at the same location, when the device continues
             === to periodically report a location even if the device is stopped.
             -->
             
            <Property key="estimateOdometer">false</Property>
            <!-- 
             === "estimateOdometer" - If true, the DCS will calculate the current event odometer
             === based on the distance traveled since the last valid GPS location
             -->
             
            <Property key="simulateGeozones">true</Property>
            <!--
             === "simulateGeozones" - If true, the DCS will check for geozone arrivals/departures
             === and insert the appropriate arrive/depart events.
             -->
 
            <Property key="tcpIdleTimeoutMS">0</Property>
            <Property key="tcpPacketTimeoutMS">0</Property>
            <Property key="tcpSessionTimeoutMS">0</Property>
            <!-- 
             === TCP Connection timeouts
             -->

            <Property key="udpIdleTimeoutMS">3000</Property>
            <Property key="udpPacketTimeoutMS">4000</Property>
            <Property key="udpSessionTimeoutMS">10000</Property>
            <!-- 
             === UDP Connection timeouts
             -->

            </Properties>
            
    </DCServer>

    <!-- ================================================================================ -->
    <DCServer name="icare">
    
        <!--
         === DCS Description
         -->
        <Description><![CDATA[
            ICare
            ]]></Description>
            
        <!-- 
         === Possible Unique-ID prefixes ("*" means that the mobile-id is used as-is)
         === Example: If the mobile-id is "123456789012345", then the "Unique ID" value
         === set in the Device admin page can be one of the following:
         ===   imei_123456789012345
         ===   123456789012345
         ===   <etc.>
         -->
        <UniqueIDPrefix><![CDATA[
            icare_
            imei_
            *
            ]]></UniqueIDPrefix>
            
        <!-- 
         === Listen ports
         -->
        <ListenPorts 
            tcpPort="31160" 
            udpPort="31160"
            />
            
        <!--
         === DCS runtime properties
         -->
        <Properties>
            </Properties>
            
    </DCServer>

    <!-- ================================================================================ -->
    <DCServer name="tk10x">
    
        <!--
         === DCS Description
         -->
