=== GBPA/OpenGTS/private.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!ELEMENT PrivateLabels (SupportedLocales, TimeZones, Properties*, Pushpins*, Domain+)>

<!-- SupportedLocales -->
<!ELEMENT SupportedLocales (Locale+)>
<!ELEMENT Locale (#PCDATA)>
	<!ATTLIST Locale id   CDATA #REQUIRED>
	<!ATTLIST Locale i18n CDATA #IMPLIED>

<!-- Timezones -->
<!ELEMENT TimeZones (#PCDATA)>

<!-- Domain -->
<!ELEMENT Domain (BaseURL?, Alias*, DefaultLoginAccount?, DefaultLoginUser?, I18N*, Copyright, PageTitle, DateFormat, TimeFormat, TimeZones?, EMailAddresses+, Properties*, Pushpins*, MapProvider+, ReverseGeocodeProvider*, GeocodeProvider*, MobileLocationProvider*, Acls, JSPEntries?, WebPages, Reports?, EventNotificationEMail?, StandardRules?, StatusCodes?, MapShapes*, Include*)>
	<!ATTLIST Domain name CDATA #REQUIRED>
	<!ATTLIST Domain host CDATA #REQUIRED>
	<!ATTLIST Domain allowLogin   (true | false) #IMPLIED>
	<!ATTLIST Domain accountLogin (true | false) #IMPLIED>
	<!ATTLIST Domain userLogin    (true | false) #IMPLIED>
	<!ATTLIST Domain emailLogin   (true | false) #IMPLIED>
	<!ATTLIST Domain showPassword (true | false) #IMPLIED>
	<!ATTLIST Domain restricted   (true | false) #IMPLIED>
	<!ATTLIST Domain demo         (true | false) #IMPLIED>
	<!ATTLIST Domain locale CDATA #IMPLIED>
    
<!-- BaseURL -->
<!ELEMENT BaseURL (#PCDATA)>

<!-- Alias -->
<!ELEMENT Alias (#PCDATA)>
	<!ATTLIST Alias host CDATA #REQUIRED>

<!-- DefaultLoginAccount -->
<!ELEMENT DefaultLoginAccount (#PCDATA)>

<!-- DefaultLoginUser -->
<!ELEMENT DefaultLoginUser (#PCDATA)>

<!-- Copyright -->
<!ELEMENT Copyright (#PCDATA)>

<!-- PageTitle -->
<!ELEMENT PageTitle (#PCDATA)>
	<!ATTLIST PageTitle i18n CDATA #IMPLIED>

<!-- DateFormat/TimeFormat -->
<!ELEMENT DateFormat (#PCDATA)>
<!ELEMENT TimeFormat (#PCDATA)>

<!-- EMailAddresses/EMailAddress -->
<!ELEMENT EMailAddresses (EMailAddress*)>
	<!ATTLIST EMailAddresses domain CDATA #IMPLIED>
<!ELEMENT EMailAddress (#PCDATA)>
	<!ATTLIST EMailAddress type (password | accounts| support | notify) #IMPLIED>

<!-- I18N/String -->
<!ELEMENT I18N (String*)>
<!ELEMENT String (#PCDATA)>
	<!ATTLIST String key CDATA #REQUIRED>
	<!ATTLIST String i18n CDATA #REQUIRED>

<!-- Properties/Property -->
<!ELEMENT Properties (Property*)>
	<!ATTLIST Properties rtPropPrefix CDATA #IMPLIED>

<!ELEMENT Property (#PCDATA)>
	<!ATTLIST Property key   CDATA #REQUIRED>
	<!ATTLIST Property rtKey CDATA #REQUIRED>

<!-- MapProvider -->
<!ELEMENT MapProvider (Property*, Pushpins*, IconSelector*, Legend*)>
	<!ATTLIST MapProvider name CDATA #REQUIRED>
	<!ATTLIST MapProvider active (true | false) #REQUIRED>
	<!ATTLIST MapProvider class CDATA #REQUIRED>
	<!ATTLIST MapProvider key CDATA #IMPLIED>
	<!ATTLIST MapProvider rtPropPrefix CDATA #IMPLIED>

<!-- MapProvider/IconSelector -->
<!ELEMENT IconSelector (#PCDATA)>
	<!ATTLIST IconSelector type (device | fleet) #REQUIRED>
	<!ATTLIST IconSelector ruleFactoryName CDATA #REQUIRED>

<!-- MapProvider/Legend -->
<!ELEMENT Legend (Title?, Icon*)>
	<!ATTLIST Legend type (device | fleet) #REQUIRED>

<!-- Pushpins/Pushpin -->
<!ELEMENT Pushpins (Pushpin*)>
    <!ATTLIST Pushpins baseURL        CDATA #IMPLIED>
    <!ATTLIST Pushpins includeDefault (true | false) #IMPLIED>
<!ELEMENT Pushpin EMPTY>
    <!ATTLIST Pushpin key             CDATA #REQUIRED>
    <!ATTLIST Pushpin alias           CDATA #IMPLIED>
    <!ATTLIST Pushpin icon            CDATA #IMPLIED>
    <!ATTLIST Pushpin eval            CDATA #IMPLIED>
    <!ATTLIST Pushpin iconSize        CDATA #IMPLIED>
    <!ATTLIST Pushpin iconOffset      CDATA #IMPLIED>
    <!ATTLIST Pushpin iconEval (true | false) #IMPLIED>
    <!ATTLIST Pushpin shadow          CDATA #IMPLIED>
    <!ATTLIST Pushpin shadowSize      CDATA #IMPLIED>
    <!ATTLIST Pushpin back            CDATA #IMPLIED>
    <!ATTLIST Pushpin backSize        CDATA #IMPLIED>
    <!ATTLIST Pushpin backOffset      CDATA #IMPLIED>
    <!ATTLIST Pushpin image           CDATA #IMPLIED>

<!-- ReverseGeocodeProvider -->
<!ELEMENT ReverseGeocodeProvider (Property*)>
	<!ATTLIST ReverseGeocodeProvider name CDATA #REQUIRED>
	<!ATTLIST ReverseGeocodeProvider active (true | false) #REQUIRED>
	<!ATTLIST ReverseGeocodeProvider geocode (true | false) #IMPLIED>
	<!ATTLIST ReverseGeocodeProvider class CDATA #REQUIRED>
	<!ATTLIST ReverseGeocodeProvider key CDATA #IMPLIED>
	<!ATTLIST ReverseGeocodeProvider rtPropPrefix CDATA #IMPLIED>

<!-- GeocodeProvider -->
<!ELEMENT GeocodeProvider (Property*)>
	<!ATTLIST GeocodeProvider name CDATA #REQUIRED>
	<!ATTLIST GeocodeProvider active (true | false) #REQUIRED>
	<!ATTLIST GeocodeProvider class CDATA #REQUIRED>
	<!ATTLIST GeocodeProvider key CDATA #IMPLIED>
	<!ATTLIST GeocodeProvider rtPropPrefix CDATA #IMPLIED>

<!-- MobileLocationProvider -->
<!ELEMENT MobileLocationProvider (Property*)>
	<!ATTLIST MobileLocationProvider name CDATA #REQUIRED>
	<!ATTLIST MobileLocationProvider active (true | false) #REQUIRED>
	<!ATTLIST MobileLocationProvider class CDATA #REQUIRED>
	<!ATTLIST MobileLocationProvider key CDATA #IMPLIED>
	<!ATTLIST MobileLocationProvider rtPropPrefix CDATA #IMPLIED>

<!-- Acls/Acl -->
<!ELEMENT Acls (Acl+)>
	<!ATTLIST Acls default (0 | 1 | 2| 3) #REQUIRED>
<!ELEMENT Acl (#PCDATA)>
	<!ATTLIST Acl name CDATA #REQUIRED>
	<!ATTLIST Acl maximum (0 | 1 | 2 | 3) #REQUIRED>
	<!ATTLIST Acl default (0 | 1 | 2 | 3) #REQUIRED>
	<!ATTLIST Acl i18n CDATA #IMPLIED>

<!-- JSPEntries/JSP -->
<!ELEMENT JSPEntries (JSP+)>
	<!ATTLIST JSPEntriese rtPropPrefix CDATA #IMPLIED>

<!ELEMENT JSP (#PCDATA)>
	<!ATTLIST JSP name  CDATA #IMPLIED>
	<!ATTLIST JSP rtKey CDATA #IMPLIED>
	<!ATTLIST JSP file  CDATA #IMPLIED>

<!-- WebPages/Page/Link/MenuGroup/Title/Description -->
<!ELEMENT WebPages (Page+, MenuGroup+)>
	<!ATTLIST WebPages jsp          CDATA #IMPLIED>
	<!ATTLIST WebPages cssDir       CDATA #IMPLIED>
	<!ATTLIST WebPages iconDir      CDATA #IMPLIED>
	<!ATTLIST WebPages rtPropPrefix CDATA #IMPLIED>
    
<!ELEMENT Page (AclName?, NavigationDescription?, MenuDescrption?, MenuHelp?, Icon?, AltIcon?, Property?)>
	<!ATTLIST Page name     CDATA #REQUIRED>
	<!ATTLIST Page rtKey    CDATA #REQUIRED>
	<!ATTLIST Page class    CDATA #REQUIRED>
	<!ATTLIST Page jsp      CDATA #IMPLIED>
	<!ATTLIST Page aclName  CDATA #IMPLIED>
	<!ATTLIST Page icon     CDATA #IMPLIED>
	<!ATTLIST Page altIcon  CDATA #IMPLIED>
	<!ATTLIST Page optional CDATA #IMPLIED>
    
<!ELEMENT Link (AclName?, NavigationDescription?, MenuDescrption?, MenuHelp?, Icon?, AltIcon?)>
	<!ATTLIST Link propName CDATA #REQUIRED>
	<!ATTLIST Link url      CDATA #REQUIRED>
	<!ATTLIST Link aclName  CDATA #IMPLIED>
	<!ATTLIST Link icon     CDATA #IMPLIED>
	<!ATTLIST Link altIcon  CDATA #IMPLIED>
    
<!ELEMENT MenuGroup (Title, Description?, Page*, Link*)>
	<!ATTLIST MenuGroup name CDATA #REQUIRED>
	<!ATTLIST MenuGroup menuBar (true | false) #IMPLIED>
	<!ATTLIST MenuGroup topMenu (true | false) #IMPLIED>
    
<!ELEMENT Title (#PCDATA)>
	<!ATTLIST Title i18n CDATA #IMPLIED>
    
<!ELEMENT Description (#PCDATA)>
	<!ATTLIST Description i18n CDATA #IMPLIED>
    
<!ELEMENT ACL EMPTY>

<!ELEMENT AclName (#PCDATA)>

<!ELEMENT Icon (#PCDATA)>

<!ELEMENT AltIcon (#PCDATA)>

<!ELEMENT NavigationDescription (#PCDATA)>
	<!ATTLIST NavigationDescription i18n CDATA #IMPLIED>
    
<!ELEMENT MenuDescrption (#PCDATA)>
	<!ATTLIST MenuDescrption i18n CDATA #IMPLIED>
    
<!ELEMENT MenuHelp (#PCDATA)>
	<!ATTLIST MenuHelp i18n CDATA #IMPLIED>

<!-- Reports/Report -->
<!ELEMENT Reports (Report+)>
	<!ATTLIST Reports rtPropPrefix CDATA #IMPLIED>

<!ELEMENT Report EMPTY>
	<!ATTLIST Report name         CDATA #REQUIRED>
	<!ATTLIST Report rtKey        CDATA #REQUIRED>
	<!ATTLIST Report aclName      CDATA #IMPLIED>
	<!ATTLIST Report sysAdminOnly CDATA #IMPLIED>

<!-- EventNotificationEMail/Subject/Body -->
<!ELEMENT EventNotificationEMail (Subject, Body)>
	<!ATTLIST EventNotificationEMail from CDATA #REQUIRED>
    
<!ELEMENT Subject (#PCDATA)>
	<!ATTLIST Subject i18n CDATA #IMPLIED>
    
<!ELEMENT Body (#PCDATA)>
	<!ATTLIST Body i18n CDATA #IMPLIED>

<!-- StandardRules -->
<!ELEMENT StandardRules (Rule*)>

<!ELEMENT Rule (Description, Selector, ActionMask?, Subject?, Message?, UserEMailWrapper)>

<!-- <!ELEMENT Description (#PCDATA)>
	<!ATTLIST Description i18n CDATA #IMPLIED> -->
    
<!ELEMENT Selector (#PCDATA)>

<!ELEMENT ActionMask (#PCDATA)>

<!-- <!ELEMENT Subject (#PCDATA)>
	<!ATTLIST Subject i18n CDATA #IMPLIED> -->
    
<!ELEMENT Message (#PCDATA)>
	<!ATTLIST Message i18n CDATA #IMPLIED>
    
<!ELEMENT UserEMailWrapper (#PCDATA)>

<!-- StatusCodes -->
<!ELEMENT StatusCodes (StatusCode*)>

<!ELEMENT StatusCode (#PCDATA)>
	<!ATTLIST StatusCode code CDATA #IMPLIED>
	<!ATTLIST StatusCode name CDATA #IMPLIED>
	<!ATTLIST StatusCode i18n CDATA #IMPLIED>

<!-- Include -->
<!ELEMENT Include (Property*)>
	<!ATTLIST Include dir              CDATA #IMPLIED>
	<!ATTLIST Include file             CDATA #IMPLIED>
	<!ATTLIST Include optional         CDATA #IMPLIED>
	<!ATTLIST Include ignoreDuplicates CDATA #IMPLIED>

<!-- MapShapes (experimental) -->
<!ELEMENT MapShapes (Shape*)>

<!ELEMENT Shape (Description, Data)>
	<!ATTLIST Shape name   CDATA #IMPLIED>
	<!ATTLIST Shape type   CDATA #IMPLIED>
	<!ATTLIST Shape radius CDATA #IMPLIED>
	<!ATTLIST Shape color  CDATA #IMPLIED>
	<!ATTLIST Shape zoom   CDATA #IMPLIED>
    
<!ELEMENT Data (#PCDATA)>

=== GBPA/OpenGTS/private.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE PrivateLabels SYSTEM "private.dtd" >

<PrivateLabels i18nPackage="org.opengts.db">

<!--
  =======================================================================================
  Project: OpenGTS - Open GPS Tracking System
  URL    : http://www.opengts.org
  File   : private.xml
  =======================================================================================
  Notes:
    - The data format of this XML file is subject to change.
    - A general tutorial on XML syntax can be found at "http://en.wikipedia.org/wiki/Xml"
    - Value substitution variables are now in use in some values defined in this file.
      They appear in the form "${Variable=defaultValue}", where "Variable" is a runtime
      variable defined in one of the runtime property files ("default.conf","webapp.conf",
      or "common.conf", etc), and "defaultValue" is the value to use for the substitution
      if the named "Variable" is not found in the loaded runtime configuration files.
      In all cases where you find "${Variable=defaultValue}", you can replace this sequence
      with your own customized value "myValue".  For instance, the "locale" attribute
      on the "Domain" tag currently specifies the following:
         locale="en"
      If you wanted to set the current locale to Spanish, you replace this value with
         locale="es"
    - For "Property" tag specifications (parent tags "Properties", "MapProvider", and
      "ReverseGeocodeProvider"), the key/value may be overidden in the 'config.conf' file.
      The parent for the specified "Property" tag will contain an attribute "rtPropPrefix"
      The value of this attribute indicates the property key prefix that can be used to
      identify a specific property override in the 'config.conf' file.  For instance,
      the following property specification exists below:
        <Properties rtPropPrefix="Domain.Properties.">
           ...
           <Property key="topMenu.showMenuHelp">true</Property>
           ...
        </Properties>
      This means that the property value can be overidden in a 'config.conf' as follows:
        Domain.Properties.topMenu.showMenuHelp=false
  =======================================================================================
  Change History:
   2008/02/07  Martin D. Flynn
      -Added 'i18n' attributes to displayable text to allow Localization.
   2008/02/21  Martin D. Flynn
      -Under the 'Domain' tag, replaced 'dateFormat' attribute with 'DateFormat' tag.
      -Under the 'Domain' tag, replaced 'timeFormat' attribute with 'TimeFormat' tag.
      -Added a few Europian timezones.
   2008/04/11  Martin D. Flynn
      -Modified MapProvider to allow specifying property key/values in separate tags.
   2008/05/14  Martin D. Flynn
      -Modified ReverseGeocodeProvider to allow specifying property key/val in separate tags.
      -Added parent 'EMailAddresses' tag to 'EMailAddress' tags.
   2008/06/20  Martin D. Flynn
      -Added MapProvider section for Mapstraction support.
   2008/07/08  Martin D. Flynn
      -Additional changes to mapping support (Mapstraction, OpenLayers, etc).
   2008/07/21  Martin D. Flynn
      -The PageDecorations tag is now obsolete and has been removed from this 'private.xml'.
       Page decorations are now handled by the JSP file at "war/track/jsp/loginSession.jsp".
      -The attribute 'jsp' has been added to 'WebPages' and 'Pages' tags to allow specifying
       a JSP to control the page look-and-feel.
   2008/07/27  Martin D. Flynn
      -Added 'Pushpins' tag section to parent 'MapProvider' tag.
   2008/08/15  Martin D. Flynn
      -Added Acl tag 'maximum' (was 'access') and 'default' attirbutes.
   2008/09/12  Martin D. Flynn
      -Added Domain properties "trackMap.showTimezoneSelection", "trackMap.showLastLocation"
   2008/09/19  Martin D. Flynn
      -Added "map.view" property support to MapProvider properties.
      -Replaced property "trackMap.showLastLocation" with "trackMap.showUpdateLast".
   2008/10/16  Martin D. Flynn
      -Simplified ACL usage (attribute "maximum" changed to "values", reduced number of ACLs).
      -Added additional Domain Properties 
   2008/12/01  Martin D. Flynn
      -Global Domain Property tags have now been placed in a "Properties" parent tag.
   2009/01/01  Martin D. Flynn
      -Added Calendar property "calendar.firstDayOfWeek".
   2009/02/01  Martin D. Flynn
      -Added "<I18N>" tag section.
   2009/02/20  Martin D. Flynn
      -Various tag attribute and body-values may now have a value specification that resembles
       something like "${Domain.key=defaultValue}".  This means that when the value for this
       attribute or tag body is evaluated, it will first attempt to obtain the value from
       the runtime property definition file (ie. default.conf, webapp.conf, or common.conf).
       If the specified key is not found in the runtime property files, then the value
       specified for 'default' will be returned.
   2009/05/01  Martin D. Flynn
      -Added "StatusCodes" section for overriding the default status code descriptions.
   2009/08/23  Martin D. Flynn
      -Added "Legend" and "IconSelector" tags to MapProvider
   2009/09/23  Martin D. Flynn
      -Removed "${Domain....=}" variable substitution (to simplify configuration of open-source version)
   2010/01/28  Martin D. Flynn
      -Move Pushpins to common global area
   2010/10/13  Martin D. Flynn
      -Added SupportedLocales
  =======================================================================================
-->

<!-- ==================================================================================== -->
<!-- Supported Locales  ================================================================= -->
<!-- This list is used to populate the language selection pull-down menu on the login page.
 === To display the language selection pull-down menu on the login page, make sure that the
 === property "accountLogin.showLocaleSelection" is set to true.
 -->
<SupportedLocales>
<!-- Locale id="ar" i18n="PrivateXML.locale.arabic"    >Arabic</Locale -->
    <Locale id="en" i18n="PrivateXML.locale.english"   >English</Locale>
    <Locale id="fr" i18n="PrivateXML.locale.french"    >French</Locale>
    <Locale id="de" i18n="PrivateXML.locale.german"    >German</Locale>
    <Locale id="el" i18n="PrivateXML.locale.greek"     >Greek</Locale>
    <Locale id="hu" i18n="PrivateXML.locale.hungarian" >Hungarian</Locale>
    <Locale id="it" i18n="PrivateXML.locale.italian"   >Italian</Locale>
<!-- Locale id="lo" i18n="PrivateXML.locale.lao"       >Lao</Locale -->
    <Locale id="nl" i18n="PrivateXML.locale.dutch"     >Dutch</Locale>
    <Locale id="pl" i18n="PrivateXML.locale.polish"    >Polish</Locale>
    <Locale id="pt" i18n="PrivateXML.locale.portuguese">Portuguese</Locale>
    <Locale id="ro" i18n="PrivateXML.locale.romanian"  >Romanian</Locale>
    <Locale id="ru" i18n="PrivateXML.locale.russian"   >Russian</Locale>
    <Locale id="sk" i18n="PrivateXML.locale.slovak"    >Slovak</Locale>
    <Locale id="sr" i18n="PrivateXML.locale.serbian"   >Serbian</Locale>
    <Locale id="es" i18n="PrivateXML.locale.spanish"   >Spanish</Locale>
    <Locale id="tr" i18n="PrivateXML.locale.turkish"   >Turkish</Locale>
</SupportedLocales>

<!-- TimeZones  ========================================================================= -->
<!-- References:
====   http://wwp.greenwichmeantime.com/info/timezone.htm
====   http://www.worldtimezone.com
==== A list of available timezones can be found in the file 'timezones.conf'
==== These TimeZones will be shared among all of the specified PrivateLabel Domains 
-->
<TimeZones>
    US/Hawaii  US/Alaska  US/Pacific  US/Arizona  US/Mountain  US/Central  US/Eastern
    Canada/Pacific  Canada/Mountain  Canada/Central  Canada/Eastern  Canada/Atlantic
    Mexico/BajaNorte  Mexico/BajaSur  Mexico/General
    Europe/Athens  Europe/Berlin  Europe/Dublin  Europe/Helsinki  Europe/Kiev   Europe/Lisbon
    Europe/London  Europe/Madrid  Europe/Moscow  Europe/Oslo      Europe/Paris  Europe/Rome
    Europe/Stockholm  Europe/Zurich
    GMT  GMT+00:00
    GMT+01:00  GMT+02:00  GMT+03:00  GMT+04:00  GMT+05:00  GMT+05:30  GMT+06:00  GMT+06:30  GMT+07:00
    GMT+08:00  GMT+09:00  GMT+10:00  GMT+11:00  GMT+12:00  GMT+13:00  GMT+14:00  
    GMT-01:00  GMT-02:00  GMT-03:00  GMT-04:00  GMT-05:00             GMT-06:00             GMT-07:00
    GMT-08:00  GMT-09:00  GMT-10:00  GMT-11:00  GMT-12:00
</TimeZones>

<!-- ================================================================================= -->
<!-- localhost ============================================================== -->
<!--
Notes:
* Make sure you replace all occurances of "example.com" below with your own domain name.
* The 'host' attribute on the 'Domain' tag specifies to which webserver domain name the 'Domain' 
  definition refers.  Specifying 'host="*"' indicates that this 'Domain' tag should be considered 
  the default PrivateLabel Domain definition for all connections made to the server.  You may create 
  multiple 'Domain' definitions, each with their own set of attributes and features.
* The OpenGTS system has the ability to bind Account records to a specific PrivateLabel domain 
  (defined by a "Domain" tag below). This is done to provide specific access control to certain 
  services such as mapping and reverse-geocoding. (ie. when a device connects to the server to send 
  data, the PrivateLabel defined for the account is used to determine which reverse-geocoding service 
  to use to create an address from the latitude/longitude). To bind an account record to a specific 
  PrivateLabel 'Domain', set the 'privateLabelName' column in the specific account record to the 
  specified 'name' of the Domain (ie. the value of the 'name' attribute).  If an account record 
  'privateLabelName' has not been specified (ie. is blank), then the services defined in the default
